-include.env
deploy: 
forge script script/RAJ.s.sol:RAJScript\
--rpc-url https://rpc.sepolia-api.lisk.com \
--account privateKey \
--sender 0xab4d2eec381aca5147741fe7c8b6f3494be1c313 \
--broadcast \
--verify \
--verifier blockscout \
--verifier-url https://sepolia-blockscout.lisk.com/api \
-vvvv